steps:
# This step runs the unit tests on the app
- name: 'python:3.7-slim'
  id: Test
  entrypoint: /bin/sh
  args:
  - -c
  - 'pip install flask && python test.py -v'
  
# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-application:latest' , '.']

# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/python-application:latest']
  
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'python-application', '--image', 'gcr.io/$PROJECT_ID/python-application:latest', '--region', 'us-east4', '--platform', 'managed', "--allow-unauthenticated"]



images:
- 'gcr.io/$PROJECT_ID/python-application:latest'


